database_url: "vpn.db"

telegram_token: "7261016033:AAHjZs-8CfXmvygHmncveDkx3JjARsDGj9c"
api_base_url: "http://38.180.162.180:15972/FANo8CjhbNS2Fk8"
login: "hVRyaEKR1a"
password: "NynYoiGsKe"
admin_users:
# ID администратора Telegram
  - 670348974